### ISSUE TITLE
can't compile on ubuntu 14.04 64bit

### ISSUE THREAD

**Issue by Goddard** [matlo/GIMX#370]
fpsconfigApp.h:29:1: error: cannot convert ‘const wchar_t*’ to ‘const char*’ in initialization

followed these instructions
http://gimx.fr/wiki/index.php?title=Development_on_Linux

**Comment by matlo** [comment]
Looks like you are trying to compile against an unsupported wxWidgets version.
The current source code can only be compiled against wxWidgets 2.8.

**Comment by Goddard** [comment]
If I have both installed then how can I specify which to use?

Thanks

**Comment by matlo** [comment]
sudo update-alternatives --config wx-config
