### ISSUE TITLE
master branch doesn't build

### ISSUE THREAD

**Issue by Goddard** [matlo/GIMX#387]
I think this is the main issue

connectors/linux/bluetooth/bt_mgmt.c:17:28: fatal error: bluetooth/mgmt.h: No such file or directory
compilation terminated.

secondary issues?
In file included from configApp.cpp:7:0:
configApp.h:30:1: error: cannot convert ‘const wchar_t*’ to ‘const char*’ in initialization
 };
 ^
<builtin>: recipe for target 'configApp.o' failed
make[1]: *** [configApp.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from fpsconfigApp.cpp:7:0:
fpsconfigApp.h:29:1: error: cannot convert ‘const wchar_t*’ to ‘const char*’ in initialization
 };
 ^

Attempted to build on 16.04

**Comment by matlo** [comment]
The master branch only builds on 14.04.
The refactoring branch builds on 16.04.
